launguage: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t andy/react -f Dockerfile.dev .

script:
  - docker run -e CI=true andy/react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "react-app"
  env: "react-env"
  bucket_name: "elasticbeanstalk-us-east-1-522903326643"
  bucket_path: "React"
  On:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"






